server:
  port: 8064
  servlet:
    context-path: /closedcart/api

# Spring boot admin server configs
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: ciaas-server
  boot:
    admin:
      client:
        url: http://localhost:8082
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/MotoCartEnterprise
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

# Service Discovery config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# JWT config
jwt:
  secret:
    private: MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQC0Y8aqcO5SkDp2AvLDTffCsmF8ox2SXfupksLRtxyiTANJRJDLARrtdSo8X9kia6n2loPw2G5fwCmqTos1jQHbbnolpsfItgEfN7QVss52aHgA4VSBLzlufkwUDo6zJQ6gA8cDFv64XRiWzhCBIA7HySy3oYq6zuQ0gSHTdne7/jV1qL3D8t/JJz8/y+FWZy6JbhHcyD/JXLl7m5MQ99QMgFjhuxwbLyz2ncWVRqwQdOdflLkoX9S14GBuO2jA2NH+CRj1ikOHohZ1ZVe4415mMykSgSoeq49dZZb7ghmmvRDMsn2nc7QmJyRfS9g1CTxDavZ8KWt90pf+owmar88dAgMBAAECgf8lWILIxpiQf0ubIwEfbgTdShDkvOBibRKtCLVMtZw3/YSwpoFThecNQjR8S1uoxKFra73lHum66Q23NIudipPX2gdvxBeYdhXFYMLnux0DZp1xkTTtidlaBsu5W0ovzHw6pI2PFjOl96AfmInSMdDdi8i2O7t88VhNhm56WQxw3tcZ/2GLRbedEX9F94z20fIcafKeAlNog5sBxucp2ehhY5PD1qFQKIjEoJB2dVrjkRKVaqmTH81Bzv3NHXWWfHRwYh5uJ2XtVww4zKOfv2ZvUHNHXYFTudqn7bEdODTHCFdZKoX5VwvP9tgpUwtjzOHHMjuXOy9zYqoUEDXs3+ECgYEA4iWZ0iR6rxNPlPUKfATV82DrJH3fJKbY0O4VTBASmRAxptZ+9HlyC3NONz0cc5gRXJjWOsxI41BipB8EUW6pr2tWopKQ/rzsZ7A/wydy3ucUjwShc0yYtxpR9zkr6t9kZmcbV0a3rIX+xTOkosoaouqmMNxmx2zm8l6YSp2vBuUCgYEAzDPcSZxQSWmYVodOUlSbU6RcAIqXRJc2jxfArLmhQ4bzIGUASLYUz8FSx99M6YJtY2ibfmbH12dfjeRvy3kWxyk3A1zTdLPSyQmCBnKXBdxFzFJjLDs4nHRtt7RGJSH3fRXbZH5gKLNtpwQySh5mCnoz0FA8eiF7/yiaQXVYq9kCgYBG3A9JqEKEzyE1hF5no8BCRVEImyQrQNhZBvDHZ5XcPhXAuB8JjXAtpFCSwGRE2BZAlGcz/0SrbUmrMUjSF0G2BIUd5ZznJN1SVAh2psq4i2GGuqW4Ef0cCnQ6acCYFK1J5O7NNwxgU5ATzG2+0GLuP2YZk0XlIPtwYDGJ18S6/QKBgDVwkQLWnJBJyStD57RWHfwqtEUT//hcVlPmVG8feVuRsojUxdlBhXrFTiOuhZNKpdPxKVhQD5aIoBIjKTqnqtVeLN59aX1OHiisi1GipXFMLxwEp52Itg0Dzz7XN9A57mnW0X6gMAwWwOiHiZ2qDOxLBMpMZTdVEf05o/zjd9wpAoGBAJF7TfdE4lIrJdTsaRYWbslCG1XqksVikoJZx78OIMdqvVo4JRGVyDNO5qlGSwWkK00NVr2t40rB8kcabYbusVTcP7/0R37fwFL0lwWedzoJCWI8GWuYCqcrEBI5zfxkBasz+Tz7TSfHdWizNrZmO4QSap2GOxjFxmL4Kfjw+fIV
    public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtGPGqnDuUpA6dgLyw033wrJhfKMdkl37qZLC0bccokwDSUSQywEa7XUqPF/ZImup9paD8NhuX8Apqk6LNY0B2256JabHyLYBHze0FbLOdmh4AOFUgS85bn5MFA6OsyUOoAPHAxb+uF0Yls4QgSAOx8kst6GKus7kNIEh03Z3u/41dai9w/LfySc/P8vhVmcuiW4R3Mg/yVy5e5uTEPfUDIBY4bscGy8s9p3FlUasEHTnX5S5KF/UteBgbjtowNjR/gkY9YpDh6IWdWVXuONeZjMpEoEqHquPXWWW+4IZpr0QzLJ9p3O0JickX0vYNQk8Q2r2fClrfdKX/qMJmq/PHQIDAQAB
  expiration:
    access-token: 900000 # 15 minutes
    refresh-token: 604800000 # 7 days

# Disable common JWT validation for now
moto-cart:
  security:
    header-auth:
      enabled: false

logging:
  level:
    root: INFO