server:
  port: 8064
  servlet:
    context-path: /closedcart

# Spring boot admin server configs
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: ciaas-server
  boot:
    admin:
      client:
        url: http://localhost:8082
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/MotoCartEnterprise
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

# Service Discovery config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# JWT config
jwt:
  secret:
    private: ${JWT_PRIVATE_KEY}
    public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtGPGqnDuUpA6dgLyw033wrJhfKMdkl37qZLC0bccokwDSUSQywEa7XUqPF/ZImup9paD8NhuX8Apqk6LNY0B2256JabHyLYBHze0FbLOdmh4AOFUgS85bn5MFA6OsyUOoAPHAxb+uF0Yls4QgSAOx8kst6GKus7kNIEh03Z3u/41dai9w/LfySc/P8vhVmcuiW4R3Mg/yVy5e5uTEPfUDIBY4bscGy8s9p3FlUasEHTnX5S5KF/UteBgbjtowNjR/gkY9YpDh6IWdWVXuONeZjMpEoEqHquPXWWW+4IZpr0QzLJ9p3O0JickX0vYNQk8Q2r2fClrfdKX/qMJmq/PHQIDAQAB
  expiration:
    access-token: 900000 # 15 minutes
    refresh-token: 604800000 # 7 days

# Disable common JWT validation for now
moto-cart:
  security:
    header-auth:
      enabled: false

logging:
  level:
    root: INFO